# Generated by Django 4.2.5 on 2023-09-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_first_name', models.CharField(max_length=20, verbose_name='Name')),
                ('teacher_last_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('teacher_age', models.IntegerField(verbose_name='Age')),
                ('experience', models.IntegerField(verbose_name='Experience')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
    ]
