# Generated by Django 4.2.5 on 2023-09-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=20, verbose_name='Name')),
                ('subject_last_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('subject_age', models.IntegerField(verbose_name='Age')),
                ('subject_group', models.CharField(max_length=1, verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Group',
            },
        ),
    ]
